QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = '無職', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'フリーランサー', payment = 10000 } } },
	bus = { label = 'バス運転手', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'ドライバー', payment = 50000 } } },
	judge = { label = '裁判官', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '裁判官', payment = 300000 } } },
	lawyer = { label = '弁護士', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'アソシエイト', payment = 300000 } } },
	reporter = { label = '記者', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '記者', payment = 50000 } } },
	trucker = { label = 'トラック運転手', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'ドライバー', payment = 50000 } } },
	tow = { label = 'レッカー', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'ドライバー', payment = 50000 } } },
	garbage = { label = 'ゴミ収集', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'コレクター', payment = 50000 } } },
	vineyard = { label = 'ブドウ園', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'ピッカー', payment = 50000 } } },
	hotdog = { label = 'ホットドッグ屋', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = '販売員', payment = 50000 } } },

    police = {
        label = '警察',
        type = 'leo',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人警官', payment = 50000 },
            ['1'] = { name = '巡査', payment = 100000 },
            ['2'] = { name = '巡査部長', payment = 150000 },
            ['3'] = { name = '警部補', isboss = true, payment = 200000 },
            ['4'] = { name = '署長', isboss = true, payment = 300000 },
        },
    },
    ambulance = {
        label = '救急',
        type = 'ems',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人隊員', payment = 50000 },
            ['1'] = { name = '救急隊員', payment = 100000 },
            ['2'] = { name = '医師', payment = 150000 },
            ['3'] = { name = '外科医', isboss = true, payment = 200000 },
            ['4'] = { name = '院長', isboss = true, payment = 300000 },
        },
    },
    realestate = {
        label = '不動産',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人営業', payment = 50000 },
            ['1'] = { name = '住宅販売員', payment = 75000 },
            ['2'] = { name = '事業販売員', payment = 100000 },
            ['3'] = { name = 'ブローカー', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    taxi = {
        label = 'タクシー',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人ドライバー', payment = 50000 },
            ['1'] = { name = 'ドライバー', payment = 75000 },
            ['2'] = { name = 'イベントドライバー', payment = 100000 },
            ['3'] = { name = '営業担当', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    cardealer = {
        label = '自動車ディーラー',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人営業', payment = 50000 },
            ['1'] = { name = 'ショールーム営業', payment = 75000 },
            ['2'] = { name = '事業営業', payment = 100000 },
            ['3'] = { name = 'ファイナンス担当', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    mechanic = {
        label = 'メカニック1',
        type = 'mechanic',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人メカニック', payment = 50000 },
            ['1'] = { name = '初級メカニック', payment = 75000 },
            ['2'] = { name = '中級メカニック', payment = 100000 },
            ['3'] = { name = '上級メカニック', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    mechanic2 = {
        label = 'メカニック2',
        type = 'mechanic',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人メカニック', payment = 50000 },
            ['1'] = { name = '初級メカニック', payment = 75000 },
            ['2'] = { name = '中級メカニック', payment = 100000 },
            ['3'] = { name = '上級メカニック', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    mechanic3 = {
        label = 'メカニック3',
        type = 'mechanic',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人メカニック', payment = 50000 },
            ['1'] = { name = '初級メカニック', payment = 75000 },
            ['2'] = { name = '中級メカニック', payment = 100000 },
            ['3'] = { name = '上級メカニック', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    beeker = {
        label = 'メカニック4',
        type = 'mechanic',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人メカニック', payment = 50000 },
            ['1'] = { name = '初級メカニック', payment = 75000 },
            ['2'] = { name = '中級メカニック', payment = 100000 },
            ['3'] = { name = '上級メカニック', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
    bennys = {
        label = 'メカニック5',
        type = 'mechanic',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = '新人メカニック', payment = 50000 },
            ['1'] = { name = '初級メカニック', payment = 75000 },
            ['2'] = { name = '中級メカニック', payment = 100000 },
            ['3'] = { name = '上級メカニック', payment = 125000 },
            ['4'] = { name = 'マネージャー', isboss = true, payment = 150000 },
        },
    },
}
